#!/usr/bin/env node

var fs = require('fs')

process.stdout.write(
  fs.readFileSync(process.argv[2], 'utf-8')
    .replace(/\\n\s*/g, '')
    .replace(/\s{2,}/g, ' ')
    .replace(/>\s+</g, '> <')
)
